apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Lab 4 RWX: adds RWX shared-storage demo (2 pods sharing a Nutanix Files PVC).
resources:
  - ../lab-04-start/frontend-only.yaml
  - ../../base/namespace.yaml
  - ../../../../apps/stateful/base/postgres-statefulset.yaml
  - ../../../../apps/stateful/base/postgres-service.yaml
  - ../../../../apps/stateful/base/rwx-demo/pvc-rwx.yaml
  - ../../../../apps/stateful/base/rwx-demo/deployment.yaml
  - ../../../../platform/quotas/resourcequota-demo-app.yaml
  - ../../../../platform/istio/destination-rules.yaml
  - ../../../../demo-wall/overlays/lab-04-rwx/
  - ../../../../loadgen/overlays/load-off/
