apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kommander-nuth-lab
  namespace: kommander
  annotations:
    ingress.kubernetes.io/force-ssl-redirect: "true"
    traefik.ingress.kubernetes.io/router.middlewares: "kommander-forwardauth@kubernetescrd"
spec:
  ingressClassName: kommander-traefik
  tls:
    - hosts:
        - kommander.nkp.nuth-lab.xyz
      secretName: nkp-nuth-lab-tls
  rules:
    - host: kommander.nkp.nuth-lab.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kommander
                port:
                  number: 80
