apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: twelve-factor
spec:
  title: "Twelve-Factor Application"
  description: "The story of AppCo — a team modernizing their monolith, one factor at a time"
  url: "https://github.com/icediceice/Nutanix-NKP-Workshop"
  workshop:
    files:
      - image:
          url: "ghcr.io/icediceice/twelve-factor-files:latest"
        includePaths:
          - /workshop/**
  session:
    namespaces:
      budget: small
      security:
        policy: baseline
    applications:
      terminal:
        enabled: true     # Light terminal use for examining sample apps
      console:
        enabled: false
      editor:
        enabled: true
      docker:
        enabled: false
      registry:
        enabled: false

    objects:
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: $(session_name)-cluster-reader
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: nkp-workshop-cluster-reader
      subjects:
      - kind: ServiceAccount
        name: $(session_name)
        namespace: $(session_namespace)
