apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-api
  namespace: demo-app
  labels:
    app: checkout-api
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkout-api
      version: v1
  template:
    metadata:
      labels:
        app: checkout-api
        version: v1
    spec:
      serviceAccountName: checkout-api
      securityContext:
        runAsNonRoot: true
      containers:
        - name: checkout-api
          image: hashicorp/http-echo:latest
          args: ["-listen=:8080", "-text=checkout-api ok"]
          ports:
            - containerPort: 8080
          env:
            - name: PAYMENT_SERVICE_URL
              value: "http://payment-mock:8080"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://opentelemetry-collector.monitoring:4317"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
