apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Lab 3 Canary 10%: 90/10 traffic split, v2 healthy.
resources:
  - ../../base/
  - ../../../../platform/istio/virtualservice-canary-10.yaml
  - ../../../../platform/quotas/resourcequota-demo-app.yaml
  - ../../../../demo-wall/overlays/lab-03-canary-10/
  - ../../../../loadgen/overlays/load-baseline/
