apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sDemoRequiredLabels
metadata:
  name: demo-required-labels
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces: ["demo-app"]
  parameters:
    labels: ["app", "version"]
