apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-loadgen
  namespace: demo-ops
  labels:
    app: demo-loadgen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-loadgen
  template:
    metadata:
      labels:
        app: demo-loadgen
        version: v1
    spec:
      containers:
        - name: loadgen
          image: fortio/fortio:latest
          command: ["fortio", "load", "-qps", "5", "-t", "0", "-c", "2", "http://checkout-api.demo-app.svc.cluster.local:8080/"]
          envFrom:
            - configMapRef:
                name: loadgen-config
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
