apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rx-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/icediceice/Nutanix-NKP-Workshop.git
    targetRevision: main
    path: workshops/nkp-workshop/apps/storefront/overlays/lab-01-start    # Changed by switch-lab.sh
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true        # Delete resources removed from Git
      selfHeal: true     # Revert manual changes
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: checkout-api    # Only allow KEDA to manage checkout-api replicas
      jsonPointers:
        - /spec/replicas
