apiVersion: v1
kind: Service
metadata:
  name: payment-mock
  namespace: demo-app
  labels:
    app: payment-mock
spec:
  selector:
    app: payment-mock
  ports:
    - name: http
      port: 8080
      targetPort: 8080
