apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-data
  namespace: demo-app
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nutanix-files
  resources:
    requests:
      storage: 5Gi
