apiVersion: v1
kind: Service
metadata:
  name: catalog
  namespace: demo-app
  labels:
    app: catalog
spec:
  selector:
    app: catalog
  ports:
    - name: http
      port: 8080
      targetPort: 8080
