apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Lab 4 Deploy DB: adds PostgreSQL StatefulSet + PVC.
resources:
  - ../lab-04-start/frontend-only.yaml
  - ../../../../apps/stateful/base/postgres-statefulset.yaml
  - ../../../../apps/stateful/base/postgres-service.yaml
  - ../../../../platform/quotas/resourcequota-demo-app.yaml
  - ../../../../platform/istio/destination-rules.yaml
  - ../../../../demo-wall/overlays/lab-04-deploy-db/
  - ../../../../loadgen/overlays/load-off/
