apiVersion: v1
data:
  OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger.istio-system.svc:4317
  OTEL_SERVICE_NAMESPACE: demo-app
kind: ConfigMap
metadata:
  name: otel-shop-config-bh72k4d75m
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-api
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: catalog-api
---
apiVersion: v1
kind: Service
metadata:
  name: checkout-api
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: checkout-api
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: payment-mock
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: payment-mock
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-api-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-api
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: catalog-api
        version: v1
    spec:
      containers:
      - env:
        - name: SERVICE_NAME
          value: catalog-api
        - name: SERVICE_VERSION
          value: v1
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          valueFrom:
            configMapKeyRef:
              key: OTEL_EXPORTER_OTLP_ENDPOINT
              name: otel-shop-config-bh72k4d75m
        - name: OTEL_SERVICE_NAMESPACE
          valueFrom:
            configMapKeyRef:
              key: OTEL_SERVICE_NAMESPACE
              name: otel-shop-config-bh72k4d75m
        image: ghcr.io/icediceice/otel-shop-lite-catalog-api:v1
        imagePullPolicy: IfNotPresent
        name: app
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 300m
            memory: 384Mi
          requests:
            cpu: 100m
            memory: 128Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-api-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkout-api
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: checkout-api
        version: v1
    spec:
      containers:
      - env:
        - name: SERVICE_NAME
          value: checkout-api
        - name: SERVICE_VERSION
          value: v1
        - name: PAYMENT_URL
          value: http://payment-mock.demo-app.svc.cluster.local
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          valueFrom:
            configMapKeyRef:
              key: OTEL_EXPORTER_OTLP_ENDPOINT
              name: otel-shop-config-bh72k4d75m
        - name: OTEL_SERVICE_NAMESPACE
          valueFrom:
            configMapKeyRef:
              key: OTEL_SERVICE_NAMESPACE
              name: otel-shop-config-bh72k4d75m
        image: ghcr.io/icediceice/otel-shop-lite-checkout-api:v1
        imagePullPolicy: IfNotPresent
        name: app
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 300m
            memory: 384Mi
          requests:
            cpu: 100m
            memory: 128Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: frontend
        version: v1
    spec:
      containers:
      - env:
        - name: SERVICE_NAME
          value: frontend
        - name: SERVICE_VERSION
          value: v1
        - name: CATALOG_URL
          value: http://catalog-api.demo-app.svc.cluster.local
        - name: CHECKOUT_URL
          value: http://checkout-api.demo-app.svc.cluster.local
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          valueFrom:
            configMapKeyRef:
              key: OTEL_EXPORTER_OTLP_ENDPOINT
              name: otel-shop-config-bh72k4d75m
        - name: OTEL_SERVICE_NAMESPACE
          valueFrom:
            configMapKeyRef:
              key: OTEL_SERVICE_NAMESPACE
              name: otel-shop-config-bh72k4d75m
        image: ghcr.io/icediceice/otel-shop-lite-frontend:v1-story-20260219f
        imagePullPolicy: IfNotPresent
        name: app
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 300m
            memory: 384Mi
          requests:
            cpu: 100m
            memory: 128Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-mock-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-mock
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: payment-mock
        version: v1
    spec:
      containers:
      - env:
        - name: SERVICE_NAME
          value: payment-mock
        - name: SERVICE_VERSION
          value: v1
        - name: FAIL_MODE
          value: ok
        - name: LATENCY_MS
          value: "0"
        - name: ERROR_RATE
          value: "0"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          valueFrom:
            configMapKeyRef:
              key: OTEL_EXPORTER_OTLP_ENDPOINT
              name: otel-shop-config-bh72k4d75m
        - name: OTEL_SERVICE_NAMESPACE
          valueFrom:
            configMapKeyRef:
              key: OTEL_SERVICE_NAMESPACE
              name: otel-shop-config-bh72k4d75m
        image: ghcr.io/icediceice/otel-shop-lite-payment-mock:v1
        imagePullPolicy: IfNotPresent
        name: app
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 300m
            memory: 384Mi
          requests:
            cpu: 100m
            memory: 128Mi
