apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: demo-app
  labels:
    app: frontend
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      version: v1
  template:
    metadata:
      labels:
        app: frontend
        version: v1
      annotations:
        sidecar.istio.io/proxyCPU: "10m"
        sidecar.istio.io/proxyCPULimit: "200m"
        sidecar.istio.io/proxyMemory: "64Mi"
        sidecar.istio.io/proxyMemoryLimit: "256Mi"
    spec:
      serviceAccountName: frontend
      securityContext:
        runAsNonRoot: true
      containers:
        - name: frontend
          image: nginxinc/nginx-unprivileged:stable-alpine
          ports:
            - containerPort: 8080
          env:
            - name: CHECKOUT_API_URL
              value: "http://checkout-api:8080"
            - name: CATALOG_URL
              value: "http://catalog:8080"
            - name: JAEGER_QUERY_URL
              value: ""
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
