apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: checkout-api-v1-keda
  namespace: demo-app
spec:
  scaleTargetRef:
    name: checkout-api
  minReplicaCount: 0
  maxReplicaCount: 10
  cooldownPeriod: 30
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus.monitoring.svc.cluster.local:9090
        metricName: istio_requests_total
        query: |
          sum(rate(istio_requests_total{
            destination_service_name="checkout-api",
            destination_service_namespace="demo-app"
          }[1m]))
        threshold: "0.2"
